# NMAKE makefile for building open.exe with Microsoft Visual C++.

CC = cl
CFLAGS = /nologo /W4 /O2
LDFLAGS = /nologo
LDLIBS = ole32.lib shell32.lib

TARGET = open.exe
SRCS = open.c
OBJS = $(SRCS:.c=.obj)

all: $(TARGET)

$(TARGET): $(OBJS)
	link $(LDFLAGS) /OUT:$@ $(OBJS) $(LDLIBS)

.c.obj:
	$(CC) $(CFLAGS) /c $<

clean:
	-del /Q $(TARGET) $(OBJS) 2>NUL
